### ISSUE TITLE
Upgrade Angular CLI So Webpack Can Be Used

### ISSUE THREAD

**Issue by Jacob-Friesen** [Jacob-Friesen/portfolio_website#39]
Webpack is more standard so it better to use that across this project: https://github.com/angular/angular-cli/pull/1455
This will be released as a `webpack.1` release.

**Comment by Jacob-Friesen** [comment]
It works, but were a few weird errors:
* https://github.com/angular/angular/issues/10626
* https://github.com/angular/angular-cli/issues/1681

**Comment by Jacob-Friesen** [comment]
This will also require upgrading to [Angular 2-rc5](https://github.com/angular/angular/blob/master/CHANGELOG.md#200-rc5-2016-08-09). It seems that Angular CLI has that as an explicit dependency. Unfortunately, rc5 has a lot of breaking changes to unit testing.

**Comment by Jacob-Friesen** [comment]
**Todo**

- [x] Get the site running in development mode
- [ ] Ensure README now matches the new technologies
- [ ] Ensure production builds work
- [ ] Reintegrate gulp (involves fixing dependency issue above)
- [ ] Get unit tests working (rc5 changes)
- [ ] Get e2e tests working (rc5 changes)

**Comment by Jacob-Friesen** [comment]
This now works, but it could probably be done in a smoother way that integrates more directly with Webpack: http://webpack.github.io/docs/motivation.html. This will come with the documentation step.

**Comment by Jacob-Friesen** [comment]
Webpack can be used for SCSS, but it is not essential right now because it will require integration with webpack *and* how angular-cli uses it (not uses per component CSS). Here are examples on how webpack works:
**Basic setup and intro:**
http://webpack.github.io/docs/tutorials/getting-started/
**Complete explanation:**
https://blog.madewithlove.be/post/webpack-your-bags/
  - Ignore the ExtractPlugin section, it is broken
  - Also header needs "default":
      Just after defining the Header component, you forgot to include the `.default` in the require of Button and Header in the `index.js`, causing the following errors:
      Uncaught TypeError: Button is not a function
      Uncaught TypeError: Header is not a function
